### ISSUE TITLE
[proposal] deployment locking

### ISSUE THREAD

**Issue by michaeldauria** [seatgeek/hell#2]
Assuming that issue #1 is implemented, having optional locking is great for apps that take a long time to deploy. Using a combination of the `app` and `environment` should be sufficient. This would prevent any task for the combination of `app` and `environment` until the lock is released.

implementation options:
- Ruby's own `Mutex` class
- Touch a file (requires cleanup after a crash)
- Redis via the redis-lock gem (requires cleanup after a crash)

**Comment by josegonzalez** [comment]
Seems reasonable. What happens when a user does not specify `app` or `environment`? How does the mutex work in that case?

Ideally this is an optional feature, and does not bring in any extra external dependencies. `Mutex` is fine.

Note that this would need to be done within `Hell::Helpers.process_line`, as we normally use `Hell::Helpers.run_in_background!` for running tasks.

**Comment by michaeldauria** [comment]
How about the locking will only work if its turned on and both `app` and `environment` are set?

Why not have the lock occur inside the sinatra action? It could be handled by a before filter.

**Comment by josegonzalez** [comment]
Lock cannot occur in sinatra because commands are run in the background using `sh`. We can perform locking by writing some sort of pid file...
